### ISSUE TITLE
`vl-convert-python` svg output issue for scatterplots

### ISSUE THREAD

**Issue by nicolaskruchten** [vega/vl-convert#44] opened 2023-02-09 17:14 UTC
This code:

```python
from vl_convert import vegalite_to_svg
from urllib.request import urlopen
import json
prefix = "https://raw.githubusercontent.com/vega/vega-lite/next/examples/specs/"
f = "sample_scatterplot.vl.json"
spec = json.loads(urlopen(prefix + f).read())
with open("test.svg", "w") as out:
  out.write(vegalite_to_svg(spec))
```

Yields this output for me (I uploaded the actual SVG so view-source as needed):

![test](https://user-images.githubusercontent.com/203523/217887878-c4fb159c-f270-4cd6-bb9a-82deedce7a1b.svg)

I'm on MacOS 11.6 on Apple Silicon, Python 3.10 installed by `mamba`

**Comment by jonmmease** [comment] 2023-02-10 15:37
duplicate of https://github.com/vega/vl-convert/issues/43

**Closed by jonmmease** 2023-02-10 15:37 UTC
